"use client";
import { useState } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { useRouter } from "next/navigation";

export default function ClientLogin() {
  const router = useRouter(); const [loginId,setLoginId]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(e: React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch("/api/client/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({loginId,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);router.push("/");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to sign in");}finally{setLoading(false)}}
  return <main className="grid min-h-screen place-items-center bg-paper px-5"><div className="w-full max-w-md"><div className="mb-8 text-center"><div className="mx-auto grid h-11 w-11 place-items-center rounded-2xl bg-ink text-white shadow-sm">◆</div><h1 className="mt-5 text-2xl font-semibold tracking-tight">Client Portal</h1><p className="mt-2 text-sm text-neutral-500">Review project requirements and approve them before development.</p></div><form onSubmit={submit} className="rounded-3xl border border-line bg-white p-7 shadow-soft"><label className="text-sm font-medium">Login ID</label><input inputMode="numeric" maxLength={6} value={loginId} onChange={e=>setLoginId(e.target.value.replace(/\D/g,""))} placeholder="6-digit login ID" className="mt-2 mb-5 w-full rounded-xl border border-line px-4 py-3 outline-none focus:border-indigo-400"/><label className="text-sm font-medium">Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="mt-2 w-full rounded-xl border border-line px-4 py-3 outline-none focus:border-indigo-400"/>{error&&<p className="mt-3 text-sm text-rose-600">{error}</p>}<button disabled={loading} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{loading?"Signing in...":"Sign in"}<ArrowRight size={16}/></button><div className="mt-5 flex items-center gap-2 text-xs text-neutral-400"><LockKeyhole size={13}/> Access is limited to the assigned project.</div></form></div></main>
}
